### ISSUE TITLE
The result of the operation is incorrect

### ISSUE THREAD

**Issue by lhr024** [bstee615/graph-for-funcs.scala#2]
Hi, author. Thanks for your script. I have successfully run graph-for-funcs.scala. However, from the results, no valid information was obtained. Here is my source code：
"static av_cold int vdadec_init(AVCodecContext *avctx)\n\n{\n\n    VDADecoderContext *ctx = avctx->priv_data;\n\n    struct vda_context *vda_ctx = &ctx->vda_ctx;\n\n    OSStatus status;\n\n    int ret;\n\n\n\n    ctx->h264_initialized = 0;\n\n\n\n    /* init pix_fmts of codec */\n\n    if (!ff_h264_vda_decoder.pix_fmts) {\n\n        if (kCFCoreFoundationVersionNumber < kCFCoreFoundationVersionNumber10_7)\n\n            ff_h264_vda_decoder.pix_fmts = vda_pixfmts_prior_10_7;\n\n        else\n\n            ff_h264_vda_decoder.pix_fmts = vda_pixfmts;\n\n    }\n\n\n\n    /* init vda */\n\n    memset(vda_ctx, 0, sizeof(struct vda_context));\n\n    vda_ctx->width = avctx->width;\n\n    vda_ctx->height = avctx->height;\n\n    vda_ctx->format = 'avc1';\n\n    vda_ctx->use_sync_decoding = 1;\n\n    vda_ctx->use_ref_buffer = 1;\n\n    ctx->pix_fmt = avctx->get_format(avctx, avctx->codec->pix_fmts);\n\n    switch (ctx->pix_fmt) {\n\n    case AV_PIX_FMT_UYVY422:\n\n        vda_ctx->cv_pix_fmt_type = '2vuy';\n\n        break;\n\n    case AV_PIX_FMT_YUYV422:\n\n        vda_ctx->cv_pix_fmt_type = 'yuvs';\n\n        break;\n\n    case AV_PIX_FMT_NV12:\n\n        vda_ctx->cv_pix_fmt_type = '420v';\n\n        break;\n\n    case AV_PIX_FMT_YUV420P:\n\n        vda_ctx->cv_pix_fmt_type = 'y420';\n\n        break;\n\n    default:\n\n        av_log(avctx, AV_LOG_ERROR, \"Unsupported pixel format: %d\\n\", avctx->pix_fmt);\n\n        goto failed;\n\n    }\n\n    status = ff_vda_create_decoder(vda_ctx,\n\n                                   avctx->extradata, avctx->extradata_size);\n\n    if (status != kVDADecoderNoErr) {\n\n        av_log(avctx, AV_LOG_ERROR,\n\n                \"Failed to init VDA decoder: %d.\\n\", status);\n\n        goto failed;\n\n    }\n\n    avctx->hwaccel_context = vda_ctx;\n\n\n\n    /* changes callback functions */\n\n    avctx->get_format = get_format;\n\n    avctx->get_buffer2 = get_buffer2;\n\n#if FF_API_GET_BUFFER\n\n    // force the old get_buffer to be empty\n\n    avctx->get_buffer = NULL;\n\n#endif\n\n\n\n    /* init H.264 decoder */\n\n    ret = ff_h264_decoder.init(avctx);\n\n    if (ret < 0) {\n\n        av_log(avctx, AV_LOG_ERROR, \"Failed to open H.264 decoder.\\n\");\n\n        goto failed;\n\n    }\n\n    ctx->h264_initialized = 1;\n\n\n\n    return 0;\n\n\n\nfailed:\n\n    vdadec_close(avctx);\n\n    return -1;\n\n}\n"
And the result of the script run is:
![png](https://user-images.githubusercontent.com/97869335/178398736-5fef62f3-3742-42f8-afca-8728fe990b23.png)
It appears that the script did not generate valid information. Could you give me some idears about how to solve it?

**Comment by bstee615** [comment]
@lhr024  This C code looks to be syntactically valid, so I'm not sure what is the problem. You can try this updated version of this script which I have been using for my most recent research:
```
import better.files.File
import io.joern.dataflowengineoss.passes.reachingdef.ReachingDefPass
import io.joern.dataflowengineoss.passes.reachingdef.ReachingDefProblem
import io.joern.dataflowengineoss.passes.reachingdef.ReachingDefTransferFunction
import io.joern.dataflowengineoss.passes.reachingdef.ReachingDefFlowGraph
import io.joern.dataflowengineoss.passes.reachingdef.DataFlowSolver
import scala.collection.immutable.HashMap
import better.files.File

// https://stackoverflow.com/a/55967256/8999671
def toJson(query: Any): String = query match {
   case m: Map[String, Any] => s"{${m.map(toJson(_)).mkString(",")}}"
   case t: (String, Any) => s""""${t._1}":${toJson(t._2)}"""
   case ss: Seq[Any] => s"""[${ss.map(toJson(_)).mkString(",")}]"""
   case s: String => s""""$s""""
   case null => "null"
   case _ => query.toString
}

/**
  * Parse code and output info
  */
@main def exec(filename: String, runOssDataflow: Boolean = true, exportJson: Boolean = true, exportCpg: Boolean = true, exportDataflow: Boolean = true, deleteAfter: Boolean = true, overwrite: Boolean = false) = {
   val cpgFile = File(filename + ".cpg.bin")
   if (cpgFile.exists) {
      println(s"Loading CPG from $cpgFile")
      importCpg(cpgFile.toString)
   }
   else {
      println(s"Exporting CPG to $cpgFile")
      importCode(filename)
      if (runOssDataflow) {
         run.ossdataflow
      }
   }
   if (exportCpg) {
      save
      val outputFilename = filename + ".cpg.bin"
      val outputFile = File(outputFilename)
      if (!outputFile.exists) {
         println(s"Exporting CPG to $outputFilename")
         File(project.path + "/cpg.bin").copyTo(outputFile, overwrite=true)
      }
   }
   if (exportJson) {
      val nodeOutputFilename = filename + ".nodes.json"
      val edgeOutputFilename = filename + ".edges.json"
      if (!File(nodeOutputFilename).exists || !File(edgeOutputFilename).exists) {
         println(s"Exporting JSON to $nodeOutputFilename $edgeOutputFilename")
         cpg.graph.E.map(node=>List(node.inNode.id, node.outNode.id, node.label, node.propertiesMap.get("VARIABLE"))).toJson |> edgeOutputFilename
         cpg.graph.V.map(node=>node).toJson |> nodeOutputFilename
      }
   }
   if (exportDataflow) {
      val dataflowFilename = filename + ".dataflow.json"
      if (!File(dataflowFilename).exists) {
         println(s"Exporting dataflow solution to $dataflowFilename")
         val method2df = cpg.method.filter(m => m.filename != "<empty>" && m.name != "<global>").map(m => {
            val problem = ReachingDefProblem.create(m);
            val solution = new DataFlowSolver().calculateMopSolutionForwards(problem);
            val transferFunction = problem.transferFunction.asInstanceOf[ReachingDefTransferFunction];
            val numberToNode = problem.flowGraph.asInstanceOf[ReachingDefFlowGraph].numberToNode;
            val df = HashMap(
               "problem.gen" -> transferFunction.gen.map(kv => (kv._1.id.toString, kv._2.toList.sorted.map(numberToNode).map(_.id))).toSeq.sortBy(_._1).toMap,
               "problem.kill" -> transferFunction.kill.map(kv => (kv._1.id.toString, kv._2.toList.sorted.map(numberToNode).map(_.id))).toSeq.sortBy(_._1).toMap,
               "solution.in" -> solution.in.map(kv => (kv._1.id.toString, kv._2.toList.sorted.map(numberToNode).map(_.id))).toSeq.sortBy(_._1).toMap,
               "solution.out" -> solution.out.map(kv => (kv._1.id.toString, kv._2.toList.sorted.map(numberToNode).map(_.id))).toSeq.sortBy(_._1).toMap,
            );
            (m.name, df)
         }).toMap
         toJson(method2df) |> dataflowFilename
      }
   }
   if (deleteAfter) {
      delete
   }
}


```

**Comment by lhr024** [comment]
Thank you!
